### ISSUE TITLE
列印發票則必須有統編？ 那沒有統編 又要列印發票的User要如何處理？

### ISSUE THREAD

**Issue by enkuo0828** [skypc785308/ecpay_invoice#1]
>         # 6.1 * 若列印註記 = '1'(列印)時，則統一編號須有值
        if arParameters['Print'] == EcpayPrintMark.Yes:
            if len(arParameters['CustomerIdentifier']) == 0:
                arErrors.append('6:CustomerIdentifier is required.')

**Comment by enkuo0828** [comment]
並且我在其他電子發票sdk沒有看到相同的檢查
https://github.com/ECPay/Invoice_Ruby/blob/master/ecpay_invoice-2.0.0/lib/ecpay_invoice/verification.rb#L222
https://github.com/ECPay/Invoice_Ruby/blob/master/ecpay_invoice-2.0.0/lib/ecpay_invoice/verification.rb#L326

**Comment by skypc785308** [comment]
> 並且我在其他電子發票sdk沒有看到相同的檢查
> https://github.com/ECPay/Invoice_Ruby/blob/master/ecpay_invoice-2.0.0/lib/ecpay_invoice/verification.rb#L222
> https://github.com/ECPay/Invoice_Ruby/blob/master/ecpay_invoice-2.0.0/lib/ecpay_invoice/verification.rb#L326

需要做什麼修改嗎？這裡只是做個小驗證，不會真的阻止request綠界
的api
